export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'

export const REGISTER_PRODUCT_REQUEST = 'REGISTER_PRODUCT_REQUEST'
export const REGISTER_PRODUCT_SUCCESS = 'REGISTER_PRODUCT_SUCCESS'
export const REGISTER_PRODUCT_FAIL = 'REGISTER_PRODUCT_FAIL'